VM_MEMORY = 6*1024
VM_CORES = 4

Vagrant.configure('2') do |config|
  config.vm.hostname='mcf'
  config.vm.box = 'mcf-ubuntu1204-build38'
  config.vm.network :private_network, ip: '192.168.50.4'

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = 'http://bosh-lite-build-artifacts.s3.amazonaws.com/mcf/38/boshlite-virtualbox-withcf-ubuntu1204.box'
    v.customize ["modifyvm", :id, "--memory", VM_MEMORY]
    v.customize ["modifyvm", :id, "--cpus", VM_CORES]
  end

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = 'http://bosh-lite-build-artifacts.s3.amazonaws.com/mcf/38/boshlite-vmware-withcf-ubuntu1204.box'
    v.vmx["numvcpus"] = VM_CORES
    v.vmx["memsize"] = VM_MEMORY
  end

config.vm.provision :shell, :inline => "echo Please run bosh cck cf-warden to get Cloud Foundry deployment restored."

end
