Vagrant.configure('2') do |config|
  config.vm.hostname='bosh-lite'
  config.vm.box = 'boshlite-ubuntu1204'
  config.vm.network :private_network, ip: '192.168.50.4'

  config.vm.provider :virtualbox do |v, override|
    override.vm.box_url = '../boxes/virtulbox/boshlite-ubuntu1204.box'
    v.customize ["modifyvm", :id, "--memory", 3*1024]
    v.customize ["modifyvm", :id, "--cpus", 4]
  end

  config.vm.provider :vmware_fusion do |v, override|
    override.vm.box_url = '../boxes/vmware/boshlite-ubuntu1204.box'
    v.vmx["numvcpus"] = "4"
    v.vmx["memsize"] = 3 * 1024
  end

end

