#!/bin/bash

packer_bosh_dir="$( cd "$( dirname $0 )" && pwd )/packer-bosh"

mkdir -p $packer_bosh_dir

wget -qO- https://s3.amazonaws.com/bosh-lite-ci-artifacts/packer-bosh/packer-bosh.tgz | tar xz -C ${packer_bosh_dir}
if [ `uname` = "Darwin" ]; then
 packer_bin_path="${packer_bosh_dir}/bin/darwin/packer-bosh"
elif [ `uname` = "Linux" ]; then
 packer_bin_path="${packer_bosh_dir}/bin/linux/packer-bosh"
fi

cat > ${packer_bosh_dir}/.packerconfig <<EOF
{
  "provisioners": {
    "packer-bosh": "${packer_bin_path}"
  }
}
EOF

echo ${packer_bosh_dir}/.packerconfig
