#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}
CF_RELEASE_DIR=${CF_RELEASE_DIR:-$BOSH_RELEASES_DIR/cf-release}

if [[ ! -d $CF_RELEASE_DIR ]]; then
  echo "Cannot find cf-release at $CF_RELEASE_DIR; override with \$CF_RELEASE_DIR variable"
  exit 1
fi

BOSH_STATUS=$(bosh status)
EXPECTED_DIRECTOR_NAME="Bosh Lite Director"
DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')

if [[ "$(echo "$BOSH_STATUS" | grep Name)" != *"$EXPECTED_DIRECTOR_NAME"* ]]; then
  echo "Can only target $EXPECTED_DIRECTOR_NAME. Please use 'bosh target' before running this script."
  exit 1
fi

mkdir -p tmp
cp manifests/cf-stub-spiff.yml tmp/cf-stub-with-uuid.yml
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" tmp/cf-stub-with-uuid.yml

$CF_RELEASE_DIR/generate_deployment_manifest \
                                              warden \
                                              tmp/cf-stub-with-uuid.yml \
                                              $CF_RELEASE_DIR/templates/cf-minimal-dev.yml \
                                              $* > manifests/cf-manifest.yml

bosh deployment manifests/cf-manifest.yml
bosh status
