#!/bin/bash

cp manifests/cf-stub.yml manifests/cf-manifest.yml
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" manifests/cf-manifest.yml
bosh target https://192.168.50.4:25555
bosh deployment manifests/cf-manifest.yml
bosh -n diff ~/workspace/cf-release/templates/cf-aws-template.yml.erb
scripts/transform.rb -f manifests/cf-manifest.yml
