#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}
CF_RELEASE_DIR=${CF_RELEASE_DIR:-$BOSH_RELEASES_DIR/cf-release}

if [[ ! -d $CF_RELEASE_DIR ]]; then
  echo "Cannot find cf-release at $CF_RELEASE_DIR; override with \$CF_RELEASE_DIR variable"
  exit 1
fi

BOSH_STATUS=$(bosh status)
EXPECTED_DIRECTOR_NAME="Bosh Lite Director"
DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')

if [[ "$(echo "$BOSH_STATUS" | grep Name)" != *"$EXPECTED_DIRECTOR_NAME"* ]]; then
  echo "Can only target $EXPECTED_DIRECTOR_NAME. Please use 'bosh target' before running this script."
  exit 1
fi

cp manifests/cf-stub.yml manifests/cf-manifest.yml
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" manifests/cf-manifest.yml
bosh deployment manifests/cf-manifest.yml
bosh -n diff $CF_RELEASE_DIR/templates/cf-aws-template.yml.erb
scripts/transform.rb -f manifests/cf-manifest.yml
if [[ ! $(bosh releases | grep " cf-release ") ]]; then
  perl -pi -e "s/cf-release/cf/g" manifests/cf-manifest.yml
  echo "No release 'cf-release' found; switching to 'cf' release"
fi
