#!/usr/bin/env bash

set -xe

STEMCELL_FILE=latest-bosh-stemcell-warden.tgz
BOSH_LITE_IP=$(cat Vagrantfile | awk -F"'" '/private_network/ { print $2 }')

if [[ ! -e $STEMCELL_FILE ]]
then
  curl --progress-bar http://bosh-jenkins-gems-warden.s3.amazonaws.com/stemcells/latest-bosh-stemcell-warden.tgz > $STEMCELL_FILE
fi

bosh target $BOSH_LITE_IP
bosh upload stemcell --skip-if-exists $STEMCELL_FILE

cd $HOME/workspace/bosh-lite
./scripts/make_manifest_spiff

cd $HOME/workspace/cf-release
./update
MOST_RECENT_CF_RELEASE=$(ls releases/cf-*.yml | sort | grep -v "\-release" | tail -n 1)
bosh upload release $MOST_RECENT_CF_RELEASE
bosh -n deploy
